# Generated by Django 2.2.3 on 2019-07-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select.Bran')),
            ],
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select.Semes')),
            ],
        ),
        migrations.AddField(
            model_name='bran',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Select.Cou'),
        ),
    ]
