# Generated by Django 2.2.3 on 2019-07-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Select', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bran',
            old_name='link',
            new_name='linkA',
        ),
        migrations.RenameField(
            model_name='sec',
            old_name='link',
            new_name='linkC',
        ),
        migrations.RenameField(
            model_name='semes',
            old_name='link',
            new_name='linkB',
        ),
    ]
